

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ds_a?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  redis:  ### redis
    host: 106.14.56.87
    port: 10002
    password: 170322
    database: 5
    timeout: 3000ms
    jedis:
      pool:
        max-active: 500
        max-wait: -1ms
        max-idle: 100
        min-idle: 10

sharding:
  jdbc:
    datasource:
      names: ds-2017,ds-2018
      ds-2017:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ds_2017?useSSL=false
        username: root
        password: root
      ds-2018:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ds_2018?useSSL=false
        username: root
        password: root
    config:
      sharding:
        default-data-source-name: ds-2018
        props:
          sql.show: true
        tables:
          t_order:
            databaseStrategy:
              standard:
                shardingColumn: create_time
                preciseAlgorithmClassName: com.cxy.sphere.sharding.DatabasePreciseAlgorithm
                rangeAlgorithmClassName: com.cxy.sphere.sharding.DatabaseRangeAlgorithm
            actual-data-nodes: ds-2017.t_order_2017_$->{1..4},ds-2018.t_order_2018_$->{1..4}
            key-generator-column-name: order_id
            tableStrategy:
#              standard:
#                shardingColumn: create_time
#                preciseAlgorithmClassName: com.cxy.sphere.sharding.OrderTablePreciseAlgorithm
#                rangeAlgorithmClassName: com.cxy.sphere.sharding.OrderTableRangeAlgorithm2
              complex:
                shardingColumns: create_time,buyer
                algorithmClassName: com.cxy.sphere.sharding.OrderComplexShardingAlgorithm

