
server:
  port: 9330

spring:
  application:
    name: sc-auth

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9210/eureka
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${server.port}

