
server:
  port: 9320

spring:
  application:
    name: sc-zuul

zuul:
  routes:
    api-pruduct:
      path: /pruduct/**
      serviceId: sc-pruduct
    api-consumer:
      path: /consumer/**
      serviceId: sc-consumer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9210/eureka
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${server.port}

logging:
  level:
    org.springframework.cloud.netflix: debug

