
server:
  port: 9611

spring:
  application:
    name: sc-consumer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9210/eureka
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${server.port}

logging:
  level:
    org.springframework.cloud.gateway: debug

